apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP # Local within cluster but not externally public
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002
