apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: c1ff5a2f-073b-4c8c-9daf-f9c51de11e8b
  labels:
    azure.workload.identity/use: "true"
