apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: playeconomycontainerregistry.azurecr.io/playy.identity:1.0.3
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5002"
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: cosmosdb-connectionString
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: servicebus-connectionString
            - name: IdentitySettings__AdminUserPassword
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: admin-password
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002
