apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
        - name: identity
          image: playeconomyacr.azurecr.io/play.identity:1.0.10
          securityContext:
            runAsUser: 0
            privileged: true
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5002"
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: economykeyvault
            - name: IdentitySettings__PathBase
              value: /identity/svc
            - name: IdentitySettings__CertificateCerFilePath # from certificate-volume
              value: "/certificates/certificate.crt"
            - name: IdentitySettings__CertificateKeyFilePath # from certificate-volume
              value: "/certificates/certificate.key"
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10
          volumeMounts: # mount to any other volumes
            - name: certificate-volume
              mountPath: /certificates
      volumes:
        - name: certificate-volume
          secret:
            secretName: signing-cert # obtain from signing-cert.yaml Certificate
            items: # reference the signing cert key from the signing-cert service
              - key: tls.key
                path: certificate.key
              - key: tls.crt
                path: certificate.crt

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP # Local within cluster but not externally public
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: c1ff5a2f-073b-4c8c-9daf-f9c51de11e8b
  labels:
    azure.workload.identity/use: "true"
