microserviceName: "identity"

# docker image
image:
  repository: playeconomyacr.azurecr.io/play.identity
  tag: 1.0.10

# Dictionary of Enviroment Variables
envVariables:
  ASPNETCORE_URLS: "http://+:5002"
  IdentitySettings__PathBase: /identity/svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__0__RedirectUris__0: https://playeconomy-gateway.westus2.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://playeconomy-gateway.westus2.cloudapp.azure.com/authentication/logout-callback

resources:
  limits:
    memory: "256Mi"
    cpu: "300m"

# Container specifications
container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

# Sign Certificate Volume
volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

# Certificate Service
certificate:
  secretName: signing-cert
  hostname: "playeconomy-gateway.westus2.cloudapp.azure.com"

identityClientId: c1ff5a2f-073b-4c8c-9daf-f9c51de11e8b
