# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  # this will generate the version that `package-and-publish-contracts` will take as output
  generate-version:
    runs-on: ubuntu-latest

    permissions: # to publish the new tag to github
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Github Tag Bump
      id: tag_bump
      # You may pin to the exact commit or the version.
      # uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.2 # this comes from your Contracts pkg
        DEFAULT_BUMP: patch # 1.0.x
        
    outputs:
      new_version: ${{ steps.tag_bump.outputs.new_tag }} # store the generated tag
          
  # This publishes the contracts
  package-and-publish-contracts:

    runs-on: ubuntu-latest
    needs: generate-version # this job requires this to be completed

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4 # checkout the latest code
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Pack
      run: | 
        dotnet pack src/Play.Identity.Contracts/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/play.identity \
        -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg

  # This publishes the contracts
  build-and-deploy-service:
  
    runs-on: ubuntu-latest
    needs: generate-version # this job requires this to be completed

    env:
      APP_NAME: play-economy-microservices
  
    permissions:
      contents: read
      packages: write
      id-token: write 
  
    steps:
    - uses: actions/checkout@v4 # checkout the latest code
    
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.GH_PAT}}
        auth-type: oidc
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT=${{secrets.GH_PAT}}"
        tags: ${{env.APP_NAME}}.azurecr.io/play.identity:${{ needs.generate-version.outputs.new_version }}
